[package]
name = "c"
version = "0.1.0"
build = "build.rs"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[build-dependencies]
minicbor-bindgen = { path = "../../" }
cbindgen = "0.24"

[dependencies]
minicbor-sys = { path = "../../minicbor" }
